name: CI
on:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: example
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: coursier/setup-action@v1.3.3
        with:
          jvm: temurin:17
          apps: sbt
      - uses: catchpoint/workflow-telemetry-action@v2
      - run: sbt scalafmtCheckAll compile coverage +test example:test "repeat 3 example/multi-jvm:test" coverageReport coverageAggregate versionPolicyCheck documentation/makeSite
      - uses: codecov/codecov-action@v2.1.0
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}