name: Release
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  coverage:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: example
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: coursier/setup-action@v1.3.3
        with:
          jvm: temurin:17
          apps: sbt
      - name: Test and compute coverage
        run: sbt scalafmtCheckAll coverage +test example/test example/multi-jvm:test coverageReport coverageAggregate
      - name: Codecov
        uses: codecov/codecov-action@v2.1.0
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: coursier/setup-action@v1.3.3
        with:
          jvm: temurin:17
          apps: sbt
      - run: sbt versionCheck ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
      - uses: codecov/codecov-action@v2

  publishSite:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: coursier/setup-action@v1.3.3
        with:
          jvm: temurin:17
          apps: sbt
      - name: Generate website
        run: sbt documentation/makeSite
      - uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          repository-name: endless4s/endless4s-transaction.github.io
          branch: master
          token: ${{ secrets.DOC_GITHUB_TOKEN }}
          folder: documentation/target/site